spring:
  application:
    name: sahan-switch-backend

  profiles:
    active: dev

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always